package GUI;

import java.awt.Color;

public class VentanaMenuVentas extends javax.swing.JFrame {

    public VentanaMenuVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonMenu = new javax.swing.JButton();
        botonRegistrarVenta = new javax.swing.JButton();
        botonMostrarVentaMes = new javax.swing.JButton();
        botonMostrarIngresoTotalMes = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Botica TuSalud");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ventas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 170, 70));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setText("Mostrar Ingreso Total por Mes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 300, 50));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setText("Mostrar Ventas por Mes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 250, 50));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel6.setText("Registrar Venta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 170, 50));

        BotonMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonMenu.setText("Menú");
        BotonMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        BotonMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 100, 48));

        botonRegistrarVenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMenuVentasB1.png"))); // NOI18N
        botonRegistrarVenta.setBorderPainted(false);
        botonRegistrarVenta.setContentAreaFilled(false);
        botonRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 350, 80));

        botonMostrarVentaMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonMostrarVentaMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMenuVentasB2.png"))); // NOI18N
        botonMostrarVentaMes.setBorderPainted(false);
        botonMostrarVentaMes.setContentAreaFilled(false);
        botonMostrarVentaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarVentaMesActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarVentaMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 340, 80));

        botonMostrarIngresoTotalMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonMostrarIngresoTotalMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMenuVentasB3.png"))); // NOI18N
        botonMostrarIngresoTotalMes.setBorderPainted(false);
        botonMostrarIngresoTotalMes.setContentAreaFilled(false);
        botonMostrarIngresoTotalMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarIngresoTotalMesActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarIngresoTotalMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 420, 80));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMenuVentas.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVentaActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarVentas ventReg1 = new VentanaRegistrarVentas();
        ventReg1.setVisible(true);
        this.setVisible(false);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_botonRegistrarVentaActionPerformed

    private void botonMostrarVentaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarVentaMesActionPerformed
        // TODO add your handling code here:
        VentanaMostrarVentasMes ventVentaMes = new VentanaMostrarVentasMes();
        ventVentaMes.setVisible(true);
        this.setVisible(false);
        setLocationRelativeTo(null);     
    }//GEN-LAST:event_botonMostrarVentaMesActionPerformed

    private void botonMostrarIngresoTotalMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarIngresoTotalMesActionPerformed
        // TODO add your handling code here:
        VentanaMostrarIngresoTotal ventIngresoTotal = new VentanaMostrarIngresoTotal();
        ventIngresoTotal.setVisible(true);
        this.setVisible(false);
        setLocationRelativeTo(null);    
    }//GEN-LAST:event_botonMostrarIngresoTotalMesActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        VentanaInicio v_inicial = new VentanaInicio();
        this.setVisible(false);
        v_inicial.setVisible(true);
    }//GEN-LAST:event_BotonMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonMostrarIngresoTotalMes;
    private javax.swing.JButton botonMostrarVentaMes;
    private javax.swing.JButton botonRegistrarVenta;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
