package GUI;

import Codigo.*;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

public class VentanaMostrarIngresoTotal extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    Venta[] venta;
    
    public VentanaMostrarIngresoTotal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Total (S/.)");
        this.jTableProductos.setModel(modelo);
        venta = Botica.vent.obtenerArrayListaVenta();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListaMes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabelTotal = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BotonMenu = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaMes.setFont(new java.awt.Font("Berlin Sans FB", 2, 20)); // NOI18N
        ListaMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        ListaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMesActionPerformed(evt);
            }
        });
        jPanel1.add(ListaMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 200, 30));

        jTableProductos.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Total (S/.)"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 530, 260));

        jLabelTotal.setFont(new java.awt.Font("Berlin Sans FB", 2, 22)); // NOI18N
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 498, 110, 40));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Botica TuSalud");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingreso Productos por Mes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 630, 70));

        BotonMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonMenu.setText("Menú");
        BotonMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        BotonMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 100, 48));

        botonRegresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 140, 43));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 60, 40));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel5.setText("Seleccionar el mes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMostrarVentasMes.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMesActionPerformed
        // TODO add your handling code here:
        jLabelTotal.setText("");
        int numMes = ListaMes.getSelectedIndex() + 1;

        modelo.setRowCount(0);
        
        int cantVentas = Botica.vent.cantElementos();
        double total=0;
        
        for(int i = 0; i < cantVentas; i++){
            if(venta[i].getMes() == numMes){
                DetalleVenta[] detAux;
                detAux = venta[i].obtenerArrayListaDetalleVenta();
                
                int cantDetalleVenta = venta[i].contadorDetalleVenta();
                
                for(int j=0; j<cantDetalleVenta;j++){
                    Medicamento m = detAux[j].getM();
                    String[] newRow={m.getNombre(), Double.toString(detAux[j].getSubtotal())};
                    modelo.addRow(newRow);
                    
                    total = total + detAux[j].getSubtotal();  
                }
                jLabelTotal.setText(Double.toString(total));       
            }
        }
    }//GEN-LAST:event_ListaMesActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        VentanaInicio v_inicial = new VentanaInicio();
        this.setVisible(false);
        v_inicial.setVisible(true);
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        VentanaMenuVentas ventVentasInicial = new VentanaMenuVentas();
        this.setVisible(false);
        ventVentasInicial.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JComboBox<String> ListaMes;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
