package GUI;

import Codigo.*;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

public class VentanaMostrarInventario extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Medicamento[] aux;
    
    public VentanaMostrarInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Stock");
        modelo.addColumn("Precio");
        this.jTableMostrar.setModel(modelo);
        
        aux =Botica.inv.obtenerArrayDeListaMedicamento();
        
        int cantInventario = Botica.inv.cantElementos();
        
        for(int i=0;i<cantInventario;i++){
            ListaDesplegableProducto.addItem(aux[i].getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListaDesplegableProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RadioBotonSi = new javax.swing.JRadioButton();
        RadioBotonNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        botonOrdenar = new javax.swing.JButton();
        BotonMostrarTodo = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaDesplegableProducto.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        ListaDesplegableProducto.setToolTipText("Seleccionar Producto");
        ListaDesplegableProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDesplegableProductoActionPerformed(evt);
            }
        });
        jPanel1.add(ListaDesplegableProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel4.setText("Ordernar por:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 140, -1));

        RadioBotonSi.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        RadioBotonSi.setText("Si");
        RadioBotonSi.setContentAreaFilled(false);
        RadioBotonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBotonSiActionPerformed(evt);
            }
        });
        jPanel1.add(RadioBotonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        RadioBotonNo.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        RadioBotonNo.setText("No");
        RadioBotonNo.setContentAreaFilled(false);
        jPanel1.add(RadioBotonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setText("PRODUCTO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, 20));

        jTableMostrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Stock", "Tipo"
            }
        ));
        jTableMostrar.setDoubleBuffered(true);
        jScrollPane4.setViewportView(jTableMostrar);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 720, 220));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mostrar Inventario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 470, 70));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Botica TuSalud");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel8.setText("Ordenar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 110, 40));

        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre de producto", "Stock" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, 30));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel9.setText("Elegir Producto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel10.setText("Mostrar Todo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 160, 40));

        BotonRegresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonRegresar.setBorderPainted(false);
        BotonRegresar.setContentAreaFilled(false);
        BotonRegresar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 120, 31));

        botonOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMostrarInventarioB2.png"))); // NOI18N
        botonOrdenar.setBorderPainted(false);
        botonOrdenar.setContentAreaFilled(false);
        botonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(botonOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 220, 70));

        BotonMostrarTodo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonMostrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMostrarInventariob1.png"))); // NOI18N
        BotonMostrarTodo.setBorder(null);
        BotonMostrarTodo.setBorderPainted(false);
        BotonMostrarTodo.setContentAreaFilled(false);
        BotonMostrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 260, 70));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        BotonMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonMenu.setText("Menú");
        BotonMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        BotonMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 100, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaMostrarInventario.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaDesplegableProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDesplegableProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaDesplegableProductoActionPerformed

    private void RadioBotonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBotonSiActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String item = (String) ListaDesplegableProducto.getSelectedItem();
        int cantInventario = Botica.inv.cantElementos();
        int pos = 0;

        for(int i = 0; i < cantInventario; i++){
            if(aux[i].getNombre().equals(item)){
                pos=i;
            }
        }
        
        String[] newRow={aux[pos].getCodigo(),aux[pos].getNombre(), Integer.toString(aux[pos].getStock()),Double.toString(aux[pos].getPrecio())};
        modelo.addRow(newRow);
    }//GEN-LAST:event_RadioBotonSiActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        VentanaInventario v_inventario = new VentanaInventario();
        this.setVisible(false);
        v_inventario.setVisible(true);
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void BotonMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarTodoActionPerformed
        // TODO add your handling code here:
        int cantInventario = Botica.inv.cantElementos();
        modelo.setRowCount(0);
        
        if(cantInventario == 0){
            String[] newRow={"Vacio","Vacio","Vacio","Vacio"};
            modelo.addRow(newRow);
        }
        else{
            for(int i = 0; i < cantInventario; i++){
                String[] newRow={aux[i].getCodigo(),aux[i].getNombre(), Integer.toString(aux[i].getStock()),Double.toString(aux[i].getPrecio())};
                modelo.addRow(newRow);
            }
        }
    }//GEN-LAST:event_BotonMostrarTodoActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        VentanaInicio v_inicial = new VentanaInicio();
        this.setVisible(false);
        v_inicial.setVisible(true);
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String opcSeleccion = (String) jComboBox1.getSelectedItem();
        int cantInventario = Botica.inv.cantElementos();
        Medicamento m[] = null;

        if(opcSeleccion.equals("Stock")){
            //ORDENAR POR STOCK
            OperacionOrdenamiento ord = new OperacionOrdenamiento(aux,1);
            ord.implementarQuicksort();
            m = ord.getM();//Almaceamos el vector de medicamentos ordenados
        }
        else if (opcSeleccion.equals("Nombre de producto")){
            //ORDENAR POR NOMBRE
            OperacionOrdenamiento ord2 = new OperacionOrdenamiento(aux,2);
            ord2.implementarQuicksort();
            m = ord2.getM();
        }
        else if (opcSeleccion.equals("Código")){
            //ORDENAR POR CODIGO
            OperacionOrdenamiento ord3 = new OperacionOrdenamiento(aux,3);
            ord3.implementarQuicksort();
            m = ord3.getM();
        }

        for(int i = 0; i < cantInventario; i++){
            String[] newRow={m[i].getCodigo(),m[i].getNombre(), Integer.toString(m[i].getStock()),Double.toString(m[i].getPrecio())};
            modelo.addRow(newRow);
        }
    }//GEN-LAST:event_botonOrdenarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonMostrarTodo;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JComboBox<String> ListaDesplegableProducto;
    private javax.swing.JRadioButton RadioBotonNo;
    private javax.swing.JRadioButton RadioBotonSi;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonOrdenar;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableMostrar;
    // End of variables declaration//GEN-END:variables
}
