package GUI;

import Codigo.*;
import java.awt.Color;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class VentanaModificarInventario extends javax.swing.JFrame {

    Scanner entrada = new Scanner(System.in);
    
    Inventario inv = new Inventario();
    
    public VentanaModificarInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCodigoQuitar = new javax.swing.JTextField();
        TextFieldStock = new javax.swing.JTextField();
        TextFieldTipo = new javax.swing.JTextField();
        TextFieldNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotonRegresar1 = new javax.swing.JButton();
        BotonMenu1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BotonAgregarMedi = new javax.swing.JButton();
        BotonQuitarMedi = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setText("Stock:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel4.setText("QUITAR MEDICAMENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 250, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel5.setText("Precio (Unit):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        TextFieldCodigoQuitar.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        TextFieldCodigoQuitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextFieldCodigoQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoQuitarActionPerformed(evt);
            }
        });
        TextFieldCodigoQuitar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldCodigoQuitarKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldCodigoQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 260, 30));

        TextFieldStock.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        TextFieldStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldStockActionPerformed(evt);
            }
        });
        TextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldStockKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 260, 30));

        TextFieldTipo.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        TextFieldTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTipoActionPerformed(evt);
            }
        });
        TextFieldTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldTipoKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 260, 30));

        TextFieldNombre.setFont(new java.awt.Font("Berlin Sans FB", 2, 18)); // NOI18N
        TextFieldNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        TextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 260, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel6.setText("Código:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        BotonRegresar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonRegresar1.setText("Regresar");
        BotonRegresar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonRegresar1.setBorderPainted(false);
        BotonRegresar1.setContentAreaFilled(false);
        BotonRegresar1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 120, 31));

        BotonMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonMenu1.setText("Menú");
        BotonMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonMenu1.setBorderPainted(false);
        BotonMenu1.setContentAreaFilled(false);
        BotonMenu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 100, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modificar Inventario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 530, 70));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Botica TuSalud");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel10.setText("AGREGAR MEDICAMENTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 270, 30));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel11.setText("Agregar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 110, 40));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel12.setText("Quitar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 80, 40));

        BotonAgregarMedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAgregarMedi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaModificarInventarioB2.png"))); // NOI18N
        BotonAgregarMedi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAgregarMedi.setBorderPainted(false);
        BotonAgregarMedi.setContentAreaFilled(false);
        BotonAgregarMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarMediActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregarMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 220, 70));

        BotonQuitarMedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonQuitarMedi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaModificarInventarioB1.png"))); // NOI18N
        BotonQuitarMedi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonQuitarMedi.setBorderPainted(false);
        BotonQuitarMedi.setContentAreaFilled(false);
        BotonQuitarMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQuitarMediActionPerformed(evt);
            }
        });
        jPanel1.add(BotonQuitarMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 220, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaModificarInventario.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarMediActionPerformed
        // TODO add your handling code here:
        if(!TextFieldNombre.getText().equals("")&&!TextFieldStock.getText().equals("")&&!TextFieldTipo.getText().equals("")){
            //Verificamos si ya existe el codigo
            if(!existeCodigo(Integer.parseInt(TextFieldStock.getText())*5+5)){
                String nombre;
                int stock;
                double tipo;
                nombre = TextFieldNombre.getText();
                stock = Integer.parseInt(TextFieldStock.getText());
                tipo = Double.parseDouble(TextFieldTipo.getText());
                Botica.inv.agregarMedicamento(nombre, stock, tipo);
                JOptionPane.showMessageDialog(null, "Medicamento agregado correctamente");
                TextFieldNombre.setText("");
                TextFieldStock.setText("");
                TextFieldTipo.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Codigo de medicamento ya creado anteriormente", "Error", JOptionPane.WARNING_MESSAGE);
                TextFieldNombre.setText("");
                TextFieldStock.setText("");
                TextFieldTipo.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_BotonAgregarMediActionPerformed

    public boolean existeCodigo(int codigo){
        String cad = String.valueOf(codigo);
        Medicamento aux[]= Botica.inv.obtenerArrayDeListaMedicamento();
        for(int i=0;i<aux.length;i++){
            if(aux[i].getCodigo().equals(cad)){
                return true;
            }
        }
        return false;
    }
    
    private void BotonQuitarMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQuitarMediActionPerformed
        // TODO add your handling code here:
        if(!TextFieldCodigoQuitar.getText().equals("")){
            //Verificamos si el codigo existe 
            if(existeCodigo(Integer.parseInt(TextFieldCodigoQuitar.getText()))){
                String codigo;
                codigo = TextFieldCodigoQuitar.getText();
                Botica.inv.eliminarMedicamento(codigo);
                TextFieldCodigoQuitar.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Codigo de medicamento no existe ", "Error", JOptionPane.WARNING_MESSAGE);
                TextFieldCodigoQuitar.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete el campo de codigo", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BotonQuitarMediActionPerformed

    private void TextFieldCodigoQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoQuitarActionPerformed

    private void TextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldStockActionPerformed

    private void TextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTipoActionPerformed

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void BotonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar1ActionPerformed
        // TODO add your handling code here:
        VentanaInventario v_inventario = new VentanaInventario();
        this.setVisible(false);
        v_inventario.setVisible(true);
    }//GEN-LAST:event_BotonRegresar1ActionPerformed

    private void BotonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenu1ActionPerformed
        // TODO add your handling code here:
        VentanaInicio v_inicial = new VentanaInicio();
        this.setVisible(false);
        v_inicial.setVisible(true);
    }//GEN-LAST:event_BotonMenu1ActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void TextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNombreKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if (!Character.isLetter(validar) && validar != ' ') {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo NOMBRE solo requiere letras");
        }
    }//GEN-LAST:event_TextFieldNombreKeyTyped

    private void TextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldStockKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if (!Character.isDigit(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo STOCK solo requiere números");
        }
    }//GEN-LAST:event_TextFieldStockKeyTyped

    private void TextFieldTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTipoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if (!Character.isDigit(validar) && validar != '.') {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo PRECIO solo requiere números");
        }  
        if (validar == '.' && TextFieldTipo.getText().contains(".")) {
                evt.consume();
                JOptionPane.showMessageDialog(null, "El campo PRECIO solo requiere números reales");
            }
    }//GEN-LAST:event_TextFieldTipoKeyTyped

    private void TextFieldCodigoQuitarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCodigoQuitarKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if (!Character.isDigit(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El campo CODIGO solo requiere números");
        }
    }//GEN-LAST:event_TextFieldCodigoQuitarKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarMedi;
    private javax.swing.JButton BotonMenu1;
    private javax.swing.JButton BotonQuitarMedi;
    private javax.swing.JButton BotonRegresar1;
    private javax.swing.JTextField TextFieldCodigoQuitar;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldStock;
    private javax.swing.JTextField TextFieldTipo;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
