package GUI;

import Codigo.*;
import java.awt.Color;

public class VentanaInventario extends javax.swing.JFrame {

    public static Inventario inv = new Inventario();
    
    public VentanaInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonModificarInv = new javax.swing.JButton();
        ModificarMostrarInv = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Botica TuSalud");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inventario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 260, 70));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabel2.setText("Mostrar Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 220, 50));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabel5.setText("Modificar Inventario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 250, 50));

        BotonModificarInv.setBackground(new java.awt.Color(255, 255, 255));
        BotonModificarInv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonModificarInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInventarioB2.png"))); // NOI18N
        BotonModificarInv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonModificarInv.setBorderPainted(false);
        BotonModificarInv.setOpaque(false);
        BotonModificarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarInvActionPerformed(evt);
            }
        });
        jPanel1.add(BotonModificarInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 330, 80));

        ModificarMostrarInv.setBackground(new java.awt.Color(255, 255, 255));
        ModificarMostrarInv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ModificarMostrarInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInventarioB1.png"))); // NOI18N
        ModificarMostrarInv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ModificarMostrarInv.setBorderPainted(false);
        ModificarMostrarInv.setContentAreaFilled(false);
        ModificarMostrarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMostrarInvActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarMostrarInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 330, 80));

        BotonMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        BotonMenu.setText("Menú");
        BotonMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonMenu.setBorderPainted(false);
        BotonMenu.setContentAreaFilled(false);
        BotonMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 100, 48));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInventario.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonModificarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarInvActionPerformed
        // TODO add your handling code here:
        VentanaModificarInventario v_mod_inventario = new VentanaModificarInventario();
        this.setVisible(false);
        v_mod_inventario.setVisible(true);
    }//GEN-LAST:event_BotonModificarInvActionPerformed

    private void ModificarMostrarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMostrarInvActionPerformed
        // TODO add your handling code here:
        VentanaMostrarInventario v_m_inventario = new VentanaMostrarInventario();
        this.setVisible(false);
        v_m_inventario.setVisible(true);
    }//GEN-LAST:event_ModificarMostrarInvActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        VentanaInicio v_inicial = new VentanaInicio();
        this.setVisible(false);
        v_inicial.setVisible(true);
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonModificarInv;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton ModificarMostrarInv;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
