package GUI;

import java.awt.Color;

public class VentanaCargando extends javax.swing.JFrame {

    public VentanaCargando() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cargando = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BarraCargando = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cargando.setBackground(new java.awt.Color(0, 0, 0));
        Cargando.setFont(new java.awt.Font("Berlin Sans FB", 2, 36)); // NOI18N
        Cargando.setText("Cargando ");
        jPanel1.add(Cargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 270, 40));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TuSalud");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 320, 60));

        BarraCargando.setBorderPainted(false);
        jPanel1.add(BarraCargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 440, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Botica TuSalud");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        botonCerrar.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar.setText(".....");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Botica");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 240, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVentanaCargando.png"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(880, 630));
        Fondo.setPreferredSize(new java.awt.Dimension(880, 630));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar BarraCargando;
    public javax.swing.JLabel Cargando;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
