package GUI;

import java.awt.Color;

public class VentanaInicio extends javax.swing.JFrame {

    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color (0, 0, 0, 0));
	jPanel1.setBackground (new Color (0, 0, 0, 0));
        botonCerrar.setBackground (new Color (0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonInventario = new javax.swing.JButton();
        BotonVentas = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        botonCerrar2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel1.setText("Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 90, 50));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel2.setText("Inventario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 130, 50));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Botica TuSalud");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 560, 70));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Botica TuSalud");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 40));

        BotonInventario.setBackground(new java.awt.Color(255, 255, 255));
        BotonInventario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInicioB1.png"))); // NOI18N
        BotonInventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonInventario.setBorderPainted(false);
        BotonInventario.setOpaque(false);
        BotonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(BotonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 280, 80));

        BotonVentas.setBackground(new java.awt.Color(255, 255, 255));
        BotonVentas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInicioB2.png"))); // NOI18N
        BotonVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotonVentas.setBorderPainted(false);
        BotonVentas.setOpaque(false);
        BotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentasActionPerformed(evt);
            }
        });
        jPanel1.add(BotonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 270, 80));

        botonCerrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrar.setText("Cerrar");
        botonCerrar.setToolTipText("");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 110, 50));

        botonCerrar2.setForeground(new java.awt.Color(252, 96, 92));
        botonCerrar2.setText(".....");
        botonCerrar2.setToolTipText("");
        botonCerrar2.setBorder(null);
        botonCerrar2.setBorderPainted(false);
        botonCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentanaInicio.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioActionPerformed
        // TODO add your handling code here:
        VentanaInventario v_inventario = new VentanaInventario();

        v_inventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonInventarioActionPerformed

    private void BotonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentasActionPerformed
        // TODO add your handling code here:

        VentanaMenuVentas ventVentas = new VentanaMenuVentas();

        ventVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVentasActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrar2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrar2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInventario;
    private javax.swing.JButton BotonVentas;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonCerrar2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
